.TH SODACAD 1 "January 2010" "Debian GNU/Linux"
.SH NAME
SODACAD \- An apparel CAD System.
.SH DESCRIPTION
An open source pattern making CAD suite, with capabilities similar to commercial pattern making packages.
sodaCAD supports DXF-files. These DXF-files are the interface to many CAD-systems such as
AutoCAD(R) and many others.

sodaCAD has no special invocation parameters. You can find the useful
docs in /usr/share/doc/librecad
